# Generated by Django 6.0.7 on 2026-08-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('num', models.IntegerField()),
                ('sub', models.TextField()),
                ('mes', models.TextField()),
            ],
        ),
    ]
