# Generated by Django 6.0.7 on 2026-08-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='daily_products',
            field=models.BooleanField(default=False),
        ),
    ]
