# Generated by Django 6.0.7 on 2026-08-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_products_daily_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='products_desc',
        ),
    ]
